linters-settings:
    golint:
        min-confidence: 0.1
    goimports:
        local-prefixes: logur.dev/adapter/template

linters:
    enable-all: true
    disable:
        - funlen
        - wsl
        - gomnd
